# Use the official PostgreSQL image as the base image
FROM postgres:13

# Set environment variables
ENV POSTGRES_DB=nis
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=password

# Expose PostgreSQL port
EXPOSE 5432
